# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  seed: 1337

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

distributed_training:
  ddp_backend: legacy_ddp
  find_unused_parameters: true
  distributed_world_size: 8
  distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: code_teacher_1_pretraining
  data: ???
  fine_tuning: true
  label_dir: ???
  normalize: false  # must be consistent with pre-training
  labels: ["ltr"]
  single_target: true
  pad_audio: true
  random_crop: false

dataset:
  num_workers: 6
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  train_subset: train_100h
  valid_subset: dev_other

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 80000
  lr: [0.00003]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: hubert_ctc
  w2v_path: ???
  apply_mask: true
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.65
  mask_channel_prob: 0.0
  layerdrop: 0.1
  dropout: 0.1
  activation_dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
